---
- name: Output event info
  hosts: web
  gather_facts: false
  tasks:
    - name: Check for running host
      ansible.builtin.debug:
        msg:
          - ">>> WOHOO! <<<"
          - "We are at the 'Ansible Anwendertreffen'!"
          - "Also, it is Star Wars day, may the 4th be with you!!"
    - name: Update logo for index.html
      ansible.builtin.copy:
        src: "{{ lookup('ansible.builtin.env', 'PWD') }}/files/StarWarsDay.png"
        dest: /var/www/html/assets/images/computacenter.png
        mode: "0644"
