---

- name: Provision infrastructure
  hosts: localhost
  connection: local
  tasks:
    - name: Create container for EDA demo
      community.docker.docker_container:
        name: mkdocs1
        image: timgrt/rockylinux8-ansible
        state: started
        command: "/usr/sbin/init"
        cgroupns_mode: host
        tmpfs:
          - /run
          - /tmp
        volumes:
          - /sys/fs/cgroup:/sys/fs/cgroup:rw
          - /var/lib/containerd
        privileged: true
        exposed_ports:
          - 8080
        ports:
          - "8080:80/tcp"

- name: Configuring target after provisioning is complete
  ansible.builtin.import_playbook: create-mkdocs-deployment.yml
