---

- name: Event-driven automation demo for Ansible Anwendertreffen
  hosts: web
  sources:
    - name: webserver_up
      ansible.eda.url_check:
        urls:
          - http://localhost:80/ansible
        delay: 10
    - name: anwendertreffen
      ansible.eda.url_check:
        urls:
          - http://localhost:80/anwendertreffen
        delay: 10
    - name: webserver_config_watch
      ansible.eda.file_watch:
        path: /etc/httpd/conf
        recursive: true
  rules:
    - name: Output state of Best-Practice container
      condition: event.url_check.status == "up" and event.meta.source.name =="webserver_up"
      action:
        run_module:
          name: ansible.builtin.debug
          module_args:
            msg: Best-Practice Container is running

    - name: Redeploy MkDocs
      condition: event.url_check.status == "down" and event.meta.source.name =="webserver_up"
      action:
        run_playbook:
          name: configuration.yml
          extra_vars:
            redeploy: true

    - name: Output when on Anwendertreffen
      condition: event.url_check.status == "up" and event.meta.source.name =="anwendertreffen"
      action:
        run_playbook:
          name: awesome.yml
