---

- name: Start webserver
  hosts: web
  become: true
  tasks:
    - name: Ensure Webserver service is running
      ansible.builtin.service:
        name: httpd
        state: started
      notify: Open_Github_Issue
  handlers:
    - name: Open_Github_Issue
      ansible.builtin.uri:
        url: "{{ github_open_issue_project }}"
        method: POST
        headers:
          Accept: application/vnd.github+json
          Authorization: Bearer {{ github_api_token }}
          X-GitHub-Api-Version: 2022-11-28
        body:
          title: "EDA: Found a bug"
          body: "Playbook run triggered by Event-Driven automation. Check service for potential misconfiguration."
        body_format: json
        status_code: 201
      when: eda_triggered | default(false)
