---

- name: Event-driven automation demo with file_watch plugin
  hosts: localhost
  sources:
    - ansible.eda.file_watch:
        path: /tmp/important-directory
        recursive: true
  rules:
    - name: Redeploy important file
      condition: event.change == "deleted"
      action:
        run_playbook:
          name: redeploy.yml
